### ISSUE TITLE
Add valid_move function

### ISSUE THREAD

**Issue by Levi-Lesches** [Learning-Python-Team/Chess#20]
Worked on by - ZeroOne010101
Join the fun at: https://github.com/ZeroOne010101/Chess-1

**Comment by Levi-Lesches** [comment]
Any progress?

**Comment by ZeroOne010101** [comment]
Take what you can use from my fork and scrap the rest. I wrote you a slack message with an rough schematic.

**Comment by ZeroOne010101** [comment]
closed with #21 courtesy of Levi

**Comment by ZeroOne010101** [comment]
closed with #21 courtesy of Levi
