### ISSUE TITLE
Add logging so bugs can be fixed easier.

### ISSUE THREAD

**Issue by Levi-Lesches** [Learning-Python-Team/Chess#7]
Worked on by - Levi (Slack Name)

**Comment by Levi-Lesches** [comment]
At exactly what points is logging

**Comment by Levi-Lesches** [comment]
I'm thinking about when pieces are made (like where they can go from their current posistions and such), and maybe when input is received and parsed.

**Comment by ZeroOne010101** [comment]
i was thinking a logging.debug with an as detailed as possible state of the function before and after something gets changed. ill leave it up to your judgement.
if somethings not right we can always change it later :)

**Comment by Levi-Lesches** [comment]
Okay. Any requests where in which functions the logging should go?

**Comment by ZeroOne010101** [comment]
ill leave you a free hand in that. The purpose is to be able to read how the function works from them, so just put them where they accomplish that.

**Comment by Levi-Lesches** [comment]
Don't worry, I haven't forgotten about this, but in the meantime feel free to try [Birdseye](https://github.com/alexmojaki/birdseye). Simply: 

1. import it: `from birdseye import eye`
2. Annotate functions with it: 
```python
@eye 
def crazy_complicated_function(): pass
```
3. Run `birdseye` from the command line
4. Open `localhost:7777` in your browser

**Comment by ZeroOne010101** [comment]
this should be closed with #15
