### ISSUE TITLE
Add nicer draw method that draws the board and its contents in a bigger way.

### ISSUE THREAD

**Issue by Levi-Lesches** [Learning-Python-Team/Chess#8]
What specifically do we want here? On my system it looks nice (except for a slight padding issue, which I could fix)

**Comment by Levi-Lesches** [comment]
On my computer I get: 
![image](https://user-images.githubusercontent.com/20747538/63303982-720c8800-c2af-11e9-8ed8-a6510aca9597.png)

**Comment by ZeroOne010101** [comment]
i meant nicer from a code perspective. The looks are ok imo.

**Comment by Levi-Lesches** [comment]
Oh OK that makes a lot more sense. I like it too BTW, nice idea using Unicode!

**Comment by Levi-Lesches** [comment]
Closed with #9
